spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123456
    url: jdbc:mysql://124.70.159.91:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSl=false&serverTimezone=GMT
    jpa:
      show-sql: true
  redis:
    host: 124.70.159.91
    port: 6379
  rabbitmq:
    host: 124.70.159.91
    port: 5672
    username: guest
    password: guest
